"""Derive Verilator-simulatable SG13CMOS5L cell models from the PDK.

The IHP cell models route every input through a ``delayed_<PORT>`` wire that is
driven only by the ``$setuphold``/``$recrem`` timing checks inside a ``specify``
block. Verilator ignores ``specify`` blocks, so those wires stay undriven and
every sequential cell in a netlist freezes: Q never follows D.

Bridging ``delayed_<PORT>`` back to ``<PORT>`` restores exactly the behaviour a
specify-aware simulator shows when no SDF is annotated, which is the zero-delay
semantics a functional equivalence check wants anyway.

Run as a script to inspect the result:

    python3 make_sg13_models.py <pdk_stdcell_verilog_dir> <output.v>
"""

import re
import sys
from pathlib import Path

# e.g. "wire delayed_D, delayed_RESET_B, delayed_CLK;"
DECLARATION = re.compile(r'^(?P<indent>[ \t]*)wire (?P<names>delayed_[A-Za-z0-9_, ]*);[ \t]*$', re.MULTILINE)

def bridge_delayed_wires(source: str) -> tuple[str, int]:
    """Drive every ``delayed_<PORT>`` wire from the port it shadows."""

    patched = 0

    def replace(match: re.Match[str]) -> str:
        nonlocal patched
        patched += 1
        indent = match.group('indent')
        names = [name.strip() for name in match.group('names').split(',')]
        assigns = [f'{indent}assign {name} = {name.removeprefix("delayed_")};' for name in names]
        return '\n'.join([match.group(0), *assigns])

    return DECLARATION.sub(replace, source), patched


def write_models(stdcell_verilog_dir: Path, outfile: Path) -> int:
    """Concatenate the UDPs and the bridged cell models into one file."""

    udp = (stdcell_verilog_dir / 'sg13cmos5l_udp.v').read_text()
    stdcell, patched = bridge_delayed_wires((stdcell_verilog_dir / 'sg13cmos5l_stdcell.v').read_text())

    header = (
        '// Generated by make_sg13_models.py -- do not edit.\n'
        f'// Source: {stdcell_verilog_dir}\n'
        f'// {patched} cell(s) had their delayed_* wires bridged for Verilator.\n\n'
    )
    outfile.write_text(header + udp + '\n' + stdcell)

    return patched


if __name__ == '__main__':
    count = write_models(Path(sys.argv[1]), Path(sys.argv[2]))
    print(f'bridged {count} cells')
